import Head from 'next/head'
import NotYetDone from '../helpers/pages/NotYetDone'
export default function Home() {

  return (
    <div className='min-h-[100vh] w-full flex flex-col justify-center items-center'>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NotYetDone />

    </div>)
}
