import Head from 'next/head';
import NotYetDone from '../components/pages/NotYetDone';

export default function Home() {
  return (
    <div className="flex min-h-[100vh] w-full flex-col items-center justify-center">
      <Head>
        <title>COVID-19 Data Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NotYetDone />
    </div>
  );
}
