import Head from 'next/head'
export default function Home() {

  return (
    <div className='min-h-[100vh] w-full flex flex-col justify-center items-center'>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-4xl font-bold'>COVID-19 DATA TRACKER</h1>
      <h1 className='text-lg mt-4'>Work in progress. Stay tuned. </h1>

    </div>)
}
